# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test Edgartools - Parallelized

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v6
      with: 
        python-version: ${{ matrix.python-version }}
        activate-environment: true
        enable-cache: true
    - name: Run PostgreSQL container
      run: |
        docker run --name pg-limiter \
          -e POSTGRES_PASSWORD=pass \
          -e POSTGRES_DB=ratelimit \
          -p 5432:5432 \
          -d postgres \
          -c max_connections=200
    - name: Install dependencies
      run: uv sync --all-groups
    - name: Run test with coverage
      run: |
        pytest -n auto tests --ratelimit_postgres
        